### ISSUE TITLE
Unsure if this is where to ask about Minimap Images

### ISSUE THREAD

**Issue by pegs001** [AsteriskAmpersand/MHR_Tex_Chopper#2]
How exactly would I find the minimap images so that I could then replace them if possible? My endgoal is to take the same image and put the great Wirebug spots on them and then put them back in the game

**Comment by AsteriskAmpersand** [comment]
Mipmaps should be in working order. Intel DDS plugin for photoshop can correctly identify them and let you explicitly open them as layers, similarly for exporting. Same for autogenerating them, the tool will convert both ways correctly in either case. Not sure why you even care about mipmaps since those are unrelated to a texture showing in-game but they are still preserved.
